export type HtmlTaskSection = {
  id: string
  title: string
  phase: string
  tagline: string
  mission: string
  project: string
  projectBrief: string
  range: [number, number]
  tasks: string[]
}

const htmlTaskSections: HtmlTaskSection[] = [
  {
    id: 'intro-basics',
    title: 'Section 1: Introduction & Basics',
    phase: 'Phase 1 · Awakening',
    tagline: 'The Foundation Code',
    mission: "Your first mission: craft the skeleton of SimplyCode's presence and give the brand its voice.",
    project: 'index.html — "SimplyCode | Innovate Simply"',
    projectBrief: 'Bootstrap the base homepage with headings, paragraphs, and storytelling elements that welcome future customers.',
    range: [1, 30],
    tasks: [
      'What is HTML',
      'Install VS Code',
      'Create your first HTML file',
      'Understand file structure (`<!DOCTYPE html>`)',
      'Write basic `<html>`, `<head>`, `<body>`',
      'Add a `<title>`',
      'Add a simple paragraph',
      'Add a heading (`<h1>`)',
      'Add multiple headings (`h1–h6`)',
      'Use `<br>` and `<hr>`',
      'Add comments in HTML',
      'Use `<p>` for paragraphs',
      'Create multiple paragraphs',
      'Add line breaks manually',
      'Use whitespace properly',
      'Understand nesting of tags',
      'Add an `<em>` (emphasis)',
      'Add a `<strong>` (bold)',
      'Add `<b>` and `<i>` for styling text',
      'Add `<small>` and `<mark>`',
      'Add `<sub>` and `<sup>`',
      'Add `<blockquote>`',
      'Add `<q>` for inline quotes',
      'Add `<abbr>` for abbreviations',
      'Add `<cite>`',
      'Add `<address>`',
      'Use `<pre>` for preformatted text',
      'Use `<code>` for inline code',
      'Use `<kbd>` for keyboard inputs',
      'Add `<samp>` for sample output',
    ],
  },
  {
    id: 'links-images',
    title: 'Section 2: Links & Images',
    phase: 'Phase 2 · The Portal Opens',
    tagline: 'The Link Network',
    mission: "Link SimplyCode's universe together with navigation, internal anchors, and branded imagery.",
    project: 'about.html — Team & Navigation Hub',
    projectBrief: 'Create cross-page navigation, brand imagery, and anchors that guide visitors around the site.',
    range: [31, 60],
    tasks: [
      'Create a hyperlink (`<a>`)',
      'Add title attribute to link',
      'Open link in new tab (`target="_blank"`)',
      'Link to an email (`mailto:`)',
      'Link to phone number (`tel:`)',
      'Add an internal page link',
      'Create a back-to-top anchor',
      'Add an image (`<img>`)',
      'Add `alt` text to image',
      'Resize image using attributes',
      'Link an image to a page',
      'Add a favicon',
      'Understand relative vs absolute URLs',
      'Use local vs hosted images',
      'Create an image gallery',
      'Add figure (`<figure>`)',
      'Add caption (`<figcaption>`)',
      'Add responsive image attributes',
      'Add multiple images',
      'Add base64 image',
      'Embed SVG image',
      'Add `loading="lazy"` attribute',
      'Add image map basics',
      'Create clickable regions in image map',
      'Link image areas to pages',
      'Add alt text for accessibility',
      'Add decorative image (CSS later)',
      'Use `<picture>` for responsive images',
      'Add `srcset` for multiple resolutions',
      'Optimize images for performance',
    ],
  },
  {
    id: 'lists',
    title: 'Section 3: Lists',
    phase: 'Phase 3 · The Lists of Knowledge',
    tagline: 'Company Wiki',
    mission: "Document SimplyCode's offerings, values, and rituals so teammates and clients stay aligned.",
    project: 'services.html — Offerings Library',
    projectBrief: 'Capture products, processes, FAQs, and onboarding steps using ordered, unordered, and description lists.',
    range: [61, 90],
    tasks: [
      'Create unordered list (`<ul>`)',
      'Create ordered list (`<ol>`)',
      'Add list items (`<li>`)',
      'Create nested lists',
      'Change list numbering type',
      'Create a description list (`<dl>`)',
      'Add `<dt>` and `<dd>`',
      'Combine multiple lists',
      'Add custom list icons (attribute level)',
      'Add a checklist using Unicode',
      'Create navigation list',
      'Add links inside list items',
      'Combine ordered and unordered lists',
      'Create a table of contents',
      'Use `<menu>` tag',
      'Use `<menuitem>` (deprecated)',
      'Semantic meaning of lists',
      'Use `<ol start="5">`',
      'Reverse numbering in `<ol>`',
      'Use `<li value="10">`',
      'Create nested description lists',
      'Accessibility for lists',
      'Add list headers',
      'Create a FAQ list',
      'Create a multi-column list',
      'Create an emoji list',
      'List inside a paragraph (invalid, check result)',
      'Create nested ordered list for steps',
      'Create an index-like list',
      'Create a timeline list',
    ],
  },
  {
    id: 'tables',
    title: 'Section 4: Tables',
    phase: 'Phase 4 · The Ledger',
    tagline: 'Data of the Company',
    mission: 'Chart SimplyCode operations with structured data so every decision is informed and transparent.',
    project: 'dashboard.html — Operations Snapshot',
    projectBrief: 'Present team rosters, project tracking, and comparison intel with accessible, well-structured tables.',
    range: [91, 130],
    tasks: [
      'Create a basic table (`<table>`)',
      'Add table rows (`<tr>`)',
      'Add table cells (`<td>`)',
      'Add table headers (`<th>`)',
      'Create a header row',
      'Create multiple data rows',
      'Add `<caption>`',
      'Add `<thead>`, `<tbody>`, `<tfoot>`',
      'Merge cells (`colspan`)',
      'Merge rows (`rowspan`)',
      'Create a product price table',
      'Add borders',
      'Add padding and spacing',
      'Add background color to table',
      'Align text in cells',
      'Add image in table cell',
      'Add hyperlink in table cell',
      'Add nested table',
      'Create timetable layout',
      'Add striped rows',
      'Add hover effect (inline style)',
      'Add table summary',
      'Use scope attribute (`col`, `row`)',
      'Create table for contact info',
      'Add sorting hint (no JS)',
      'Accessibility attributes for tables',
      'Add `<col>` and `<colgroup>`',
      'Define column width',
      'Add footer with total value',
      'Create invoice table',
      'Create student result table',
      'Create schedule table',
      'Create comparison table',
      'Create product spec sheet',
      'Add emoji in table cells',
      'Add icon links in table',
      'Combine rowspan & colspan',
      'Create borderless table',
      'Add zebra pattern manually',
      'Validate table structure',
    ],
  },
  {
    id: 'forms',
    title: 'Section 5: Forms',
    phase: 'Phase 5 · The Gate of Forms',
    tagline: 'User Connection',
    mission: 'Open SimplyCode to the world with forms that welcome leads, clients, and community feedback.',
    project: 'contact.html & signup.html — Client Intake Flow',
    projectBrief: 'Design inclusive forms for contact, onboarding, surveys, and subscriptions with thoughtful validation.',
    range: [131, 200],
    tasks: [
      'Create a `<form>`',
      'Add `<input>` (text)',
      'Add `<label>` for input',
      'Connect label with `for` attribute',
      'Add placeholder',
      'Add required field',
      'Add email input',
      'Add password input',
      'Add number input',
      'Add date input',
      'Add time input',
      'Add color picker',
      'Add range input',
      'Add checkbox',
      'Add radio buttons',
      'Group radio buttons',
      'Add submit button',
      'Add reset button',
      'Add hidden field',
      'Add textarea',
      'Add select dropdown',
      'Add multiple selection',
      'Add optgroup',
      'Add datalist suggestions',
      'Add file upload input',
      'Add form action attribute',
      'Add form method (GET vs POST)',
      'Add autocomplete attribute',
      'Add autofocus',
      'Add pattern validation',
      'Add minlength & maxlength',
      'Add step for number input',
      'Disable field',
      'Readonly input',
      'Add custom button',
      'Add button with icon (Unicode)',
      'Create login form',
      'Create registration form',
      'Create contact form',
      'Create feedback form',
      'Create survey form',
      'Create newsletter signup',
      'Add reset form link',
      'Add form description',
      'Add placeholder examples',
      'Add form hint (`<small>`)',
      'Add required indicators (*)',
      'Add tabindex',
      'Add fieldset & legend',
      'Group fields',
      'Add input grouping visually',
      'Add form title',
      'Add aria-label',
      'Add form validation messages',
      'Create multi-section form',
      'Add submit confirmation message',
      'Use novalidate attribute',
      'Add progress bar manually',
      'Add rating stars (radio)',
      'Add terms & conditions checkbox',
      'Add file size note',
      'Add upload preview (conceptual)',
      'Create search form',
      'Add search input',
      'Add clear input button',
      'Add custom reset text',
      'Add tooltip using title attribute',
      'Add disabled button',
      'Add clickable label area',
      'Validate HTML form structure',
    ],
  },
  {
    id: 'media-embeds',
    title: 'Section 6: Media & Embeds',
    phase: 'Phase 6 · The Media Chamber',
    tagline: 'Showcase Center',
    mission: 'Stage SimplyCode’s demos, podcasts, and maps so investors and users can experience the brand.',
    project: 'showcase.html — Demo Stage',
    projectBrief: 'Embed rich media, maps, and transcripts that narrate the SimplyCode story across formats.',
    range: [201, 240],
    tasks: [
      'Embed a YouTube video',
      'Add `<video>` tag',
      'Add controls attribute',
      'Add autoplay',
      'Add loop',
      'Add muted video',
      'Add poster thumbnail',
      'Add multiple video sources',
      'Add audio file',
      'Add audio controls',
      'Add multiple audio sources',
      'Add captions to video',
      'Add `<track>` for subtitles',
      'Embed a map (Google Maps iframe)',
      'Add `<iframe>` basics',
      'Embed external webpage',
      'Add responsive iframe',
      'Add sandbox to iframe',
      'Add allowfullscreen',
      'Add custom width/height',
      'Embed code snippet in page',
      'Add download link',
      'Add `<embed>` tag',
      'Add `<object>` tag',
      'Add parameter to object',
      'Add SVG inline',
      'Add external SVG',
      'Add figure with video',
      'Create a video gallery',
      'Add autoplay + muted hero video',
      'Add media fallback text',
      'Add controlsList attribute',
      'Add preload attribute',
      'Add audio player with description',
      'Add track kind caption/subtitle',
      'Add iframe title for accessibility',
      'Add media copyright note',
      'Add podcast embed',
      'Add livestream embed',
      'Add video with transcript below',
    ],
  },
  {
    id: 'semantic-layout',
    title: 'Section 7: Semantic & Layout',
    phase: 'Phase 7 · The Semantic Tower',
    tagline: 'Structure of Simplicity',
    mission: 'Refine SimplyCode’s flagship pages with meaningful landmarks and reusable story-driven layouts.',
    project: 'index.html (semantic) — Living Layout',
    projectBrief: 'Rebuild the site structure with semantic regions, reusable sections, and accessible navigation patterns.',
    range: [241, 300],
    tasks: [
      'Use `<header>` tag',
      'Use `<footer>` tag',
      'Use `<main>`',
      'Use `<article>`',
      'Use `<section>`',
      'Use `<aside>`',
      'Use `<nav>`',
      'Use `<figure>` & `<figcaption>`',
      'Use `<time>` tag',
      'Use `<mark>` in context',
      'Create blog layout with semantic tags',
      'Create news article layout',
      'Create website header',
      'Create footer links',
      'Create navigation list',
      'Add breadcrumb nav',
      'Create sidebar',
      'Add hero section (text only)',
      'Add CTA button (link)',
      'Create about section',
      'Create contact info section',
      'Create testimonial structure',
      'Add copyright line',
      'Add logo (image)',
      'Add company name in header',
      'Add social links',
      'Add email link',
      'Add phone link',
      'Add location text',
      'Add structured layout for landing',
      'Add HTML5 semantic outline',
      'Validate section structure',
      'Add multiple `<article>` blocks',
      'Add related posts section',
      'Add author info box',
      'Add `<address>` tag',
      'Add back-to-top link',
      'Add simple sitemap layout',
      'Add navigation with IDs',
      'Add skip-to-content link',
      'Add visually hidden text',
      'Create home page structure',
      'Create blog page structure',
      'Create contact page structure',
      'Create about page structure',
      'Create FAQ structure',
      'Create team section',
      'Create features section',
      'Create pricing section',
      'Create hero tagline',
      'Create image + text section',
      'Create 2-column layout (HTML only)',
      'Add horizontal rule for separation',
      'Add multiple sections properly',
      'Create resume layout',
      'Create profile page layout',
      'Create landing page layout',
      'Create news card structure',
      'Add metadata structure (author/date)',
      'Validate semantic structure',
    ],
  },
  {
    id: 'advanced-seo-accessibility',
    title: 'Section 8: Advanced + SEO + Accessibility',
    phase: 'Phase 8 · The Meta Dimension',
    tagline: 'SEO & Accessibility Realm',
    mission: 'Prepare SimplyCode for launch with metadata, accessibility, and evergreen fallback experiences.',
    project: 'final.html — Launch-Ready Experience',
    projectBrief: 'Ship a production-ready HTML experience with SEO tags, ARIA support, and operational companion pages.',
    range: [301, 345],
    tasks: [
      'Add `<meta charset="UTF-8">`',
      'Add viewport meta',
      'Add description meta',
      'Add keywords meta',
      'Add author meta',
      'Add favicon link',
      'Add robots meta',
      'Add OpenGraph tags',
      'Add Twitter card meta',
      'Add canonical link',
      'Add language attribute',
      'Add title for accessibility',
      'Add alt text for all images',
      'Add ARIA labels',
      'Add role attributes',
      'Add skip link',
      'Add keyboard navigation',
      'Add tabindex order',
      'Add contrast-friendly text',
      'Add semantic headings',
      'Add readable title tags',
      'Add page landmarks',
      'Add screen reader text',
      'Add no-script message',
      'Add noscript fallback',
      'Add sitemap link',
      'Add 404 HTML page',
      'Add maintenance page',
      'Add contact page',
      'Add coming soon page',
      'Add privacy policy page',
      'Add terms page',
      'Add robots.txt link',
      'Add analytics placeholder',
      'Add structured data JSON-LD (conceptual)',
      'Add breadcrumb structured markup',
      'Add meta refresh redirect',
      'Add base tag',
      'Add link rel alternate',
      'Add apple-touch-icon',
      'Add theme-color meta',
      'Add manifest.json reference',
      'Add noscript note for JS users',
      'Add HTML validator check',
      'Finish final HTML project (portfolio website)',
    ],
  },
]

export const totalHtmlTasks = htmlTaskSections.reduce((sum, section) => sum + section.tasks.length, 0)

export default htmlTaskSections

